In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.model_selection import train_test_split
from wordcloud import WordCloud

%matplotlib inline

In [5]:
df = pd.read_csv('/Users/ishashree/Downloads/spam.csv',encoding='ISO-8859-1')
df.sample(10)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
1889,ham,I gotta collect da car at 6 lei.,NaN,NaN,NaN
5303,ham,"I can. But it will tell quite long, cos i have...",NaN,NaN,NaN
5168,ham,"IÛ÷ve got some salt, you can rub it in my ope...",NaN,NaN,NaN
255,ham,Don't necessarily expect it to be done before ...,NaN,NaN,NaN
4776,ham,Sorry completely forgot * will pop em round th...,NaN,NaN,NaN
3305,ham,HI DARLIN I FINISH AT 3 DO U 1 2 PICK ME UP OR...,NaN,NaN,NaN
5205,spam,Had your mobile 11mths ? Update for FREE to Or...,NaN,NaN,NaN
1773,ham,"I'm not coming over, do whatever you want",NaN,NaN,NaN
4751,ham,Well boy am I glad G wasted all night at apple...,NaN,NaN,NaN
4457,ham,Die... I accidentally deleted e msg i suppose ...,NaN,NaN,NaN

In [6]:
drops = ['Unnamed: 2','Unnamed: 3','Unnamed: 4']
df.drop(drops,axis="columns",inplace=True)
df.columns = ['label','message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.info

<bound method DataFrame.info of      label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]>

In [10]:
cv = CountVectorizer(decode_error='ignore')
X = cv.fit_transform(df['message'])

X_train, X_test, y_train, y_test = train_test_split(X, df['label'], test_size=0.3, random_state=101)

In [12]:
df['message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [13]:
df['message'][40]

'Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola'

In [14]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
print('training accuracy is : ',mnb.score(X_train,y_train)*100)
print('test accuracy is : ',mnb.score(X_test,y_test)*100)

training accuracy is :  99.41025641025641
test accuracy is :  98.56459330143541

In [15]:
def visualize(label):
    words = ''
    for msg in df[df['label']==label]['message']:
        msg = msg.lower()
        words+=msg + ' '
    wordcloud = WordCloud(width=600,height=400).generate(words)
    plt.imshow(wordcloud)
    plt.axis('off')

=>Type in your message in ‘your_message’ and run this cell and it will try its best to classify it as either spam or ham.

In [26]:
your_message = 'Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola'

your_message = cv.transform([your_message])

In [27]:
 mnb.predict(your_message)

array(['ham'], dtype='<U4')

In [28]:
ss = mnb.predict(your_message)

In [29]:
ss[0]

'ham'